---
abstract: 'Use L<Dist::Zilla> like MSCHOUT does'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Module::Signature: 0
  Socket: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101040'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-MSCHOUT
recommends: {}
requires:
  Dist::Zilla: 2.101040
  Dist::Zilla::Plugin::ArchiveRelease: 0
  Dist::Zilla::Plugin::AutoPrereq: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::BumpVersionFromGit: 0
  Dist::Zilla::Plugin::FakeRelease: 0
  Dist::Zilla::Plugin::Homepage: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::Signature: 0
  Dist::Zilla::PluginBundle::Classic: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Weaver::Section::BugsRT: 0
  Pod::Weaver::Section::SourceGitHub: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-MSCHOUT
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-MSCHOUT/
  repository: http://github.com/mschout/dist-zilla-pluginbundle-mschout
version: 0.13
